#% text_encoding = iso8859_1
 
:error_dataset    No existe un dataset llamado #1
:error_config     Configuración de exportación No válida
:error_export     Se ha producido un error durante proceso de exportación:
#1
:error_parameter  #1 no es un valor válido para el parametro #2
:no_correspondences No hay definidas correspondencias para el dataset #1
:error_cancel     Se produjo un error al intentar detener el proceso de exportación
#1
:fin_export_ok    El proceso de exportación finalizó con éxito.
:err_bound        No se ha definido un método válido para determinar los limites de la exportación
:err_geometry     No se ha definido un valor válido para determinar las geometrías del limite que se exportan (Recorte/Superposición/Dentro)
:err_projection   Sistema de coordenadas destino no válido
:err_units        Unidades destino no válidas
