#% text_encoding = iso8859_1

:title		            Exportador SHAPE

:file_name                  Ruta de Salida:
:browse                     Explorar
:ch_units                   Unidades del Fichero:
:ch_coords                  Proyección del Fichero:

:path_export_shapes         Seleccionar directorio de salida

:gb_area                    AREA
:bounds_source_chooser      Seleccionar por: 
:window_bounds_tooltip      Seleccionar el tipo de área de exportación
:window_bounds              Límites de la Ventana
:trail_bounds               Límites de Trazo
:no_bounds                 Todos

:geometry                   Geometrías:
:overlapping                Superposición
:inside                     Dentro

:gb_corresp                 CORRESPONDENCIAS SW-SHAPE
:dataset_orig               Dataset Origen
:dataset_orig_tooltip       Seleccionar dataset origen de datos
:load_default_values        Cargar XML Por Defecto
:load_xml                   Cargar XML
:save_xml                   Salvar XML
:generate_xml_all           Generar XML Completo
:advanced_config            Modificar Correspondencias
:new_config                 Crear Nuevas Correspondencias

:sel_xml_config_file        Seleccionar XML de configuración
:save_xml_config_file       Guardar la configuración actual en un XML
:generate_xml_config_all    Genera XML con todas las tablas del dataset
:xml_files                  Ficheros XML (*.xml)
:filter_xml_files           *.xml

:export                     Exportar
:interrupt                  Interrumpir
:exit                       Salir

:combos_width               220
:file_text_width            350

:err_sin_configuracion      No hay definida una configuración de exportación valida

:no_trail		    Error: No hay ningún trazo definido.
:invalid_trail_bounds_for_export Límites de trazo no válidos para exportación
